### ISSUE TITLE
VCF file

### ISSUE THREAD

**Issue by paytonyau** [HudsonAlpha/mixoviz#1]
Hi, 

I have tried to use your BAllele.py on our VCF file, and below is our bash commend, 
`Python Ballele.py vcf.gz InputSampleName output.png`

However, it came out a list of warning messages like below, 
`Warning: missing data for chromosome "NC_XXXX89.1"`
`Warning: missing data for chromosome "NC_XXXX90.1"`
`......`

I am wondering is it because of  version difference of VCF file? 
Also, that would be great if you could provide an example vcf file to compare to our file.

Thank you for your help.
Best regards,
Payton

**Comment by holtjma** [comment]
Yea, the warning comes from [this line](https://github.com/HudsonAlpha/mixoviz/blob/2f2798a1cfe950c7319f494cfba1cb8201b7589b/scripts/BAllele.py#L45) in the code, and it really is just a warning.  The trigger occurs if the chromosome name occurs in the header of your VCF, but for some reason there is no data in the VCF on that chromosome.  I think this error can also happen if you aren't using a bgzipped  and tabixed VCF file, but you appear to be using one.

**Comment by paytonyau** [comment]
Thanks for your reply. I can see that I have the outcome although I got the warning messages.

**Comment by paytonyau** [comment]
Hi, here is my feedback after using your package.
(1) It seems that the try/except bit is thrown by a dependency (=pysam).
(2) Pysam then also requires that the VCF file be zipped with bgzip, but not gzip.

**Comment by holtjma** [comment]
1) I'm not sure about the try except block, it wasn't mentioned in your initial post
2) Yes, `bgzip` + `tabix` to generate the index files is fairly standard when it comes to compressed VCF files.  Sorry if that wasn't clear in the instructions.
